import { Geist, Geist_Mono } from 'next/font/google'
import { ClerkProvider, SignedIn, SignedOut, RedirectToSignIn } from '@clerk/nextjs'
import Sidebar from './components/sidebar'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <SignedIn>
            <Sidebar>{children}</Sidebar>
          </SignedIn>
          <SignedOut>
            <RedirectToSignIn redirectUrl="/login" />
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  )
}
